<?php

namespace Database\Seeders\Banner;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BannerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('banner.banners')->insert([

            [
                'id' => '108',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//b6zdT2jXFNdqUhBMQEhT8RIkYWW696.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//CgCFfuMoxWmTFKQQECygO1Xl5QaPYY.jpg',
                'title' => 'Promo Steam Voucher',
                'highlight' => '',
                'terms' =>'<p>Promo Steam Voucher</p>',
                'activity' => 'voucher_game',
                'label' => '',
                'web' => '',
                'phone' => '',
                'email' => '',
                'time_start' => '2020-01-01 5:40:00',
                'time_end' => '2020-01-31 4:57:50',
                'group' => '',
                'params' => '{"id":"14","name":"Steam (IDR)","slug":"steam-idr"}',
                'status' => '2',
            ],
            [
                'id' => '110',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//f7ANtwi6ZfI04osRIvUUdhybhxU61E.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//YMm2oDK0UD2E6VDOVGLOzMGfLJ9fr2.jpg',
                'title' => 'Paket Data HOTROAD',
                'highlight' => '',
                'terms' =>'<p>Paket Data HOTROAD</p>',
                'activity' => 'telecom',
                'label' => '',
                'web' => '',
                'phone' => '',
                'email' => '',
                'time_start' => '2019-08-01 5:40:00',
                'time_end' => '2019-08-31 16:59:00',
                'group' => '',
                'params' => '{"id":"23","slug":"paket-data-1"}',
                'status' => '2',
            ],
            [
                'id' => '111',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//19YE8fe1W90OsZ0FhRoGkyeN1Bdnbp.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//hz9RNggo6QDBMatuGpzyua2csn3UHG.jpg',
                'title' => 'Paket Data Xtra Combo until Januari',
                'highlight' => '',
                'terms' =>'<p>Paket Data Xtra Combo</p>',
                'activity' => 'telecom',
                'label' => '',
                'web' => '',
                'phone' => '',
                'email' => '',
                'time_start' => '2019-09-30 17:00:01',
                'time_end' => '2020-01-15 16:59:00',
                'group' => '',
                'params' => '{"id":"23","slug":"paket-data-1"}',
                'status' => '2',
            ],
            [
                'id' => '112',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//Gj0hFXwefs4QoKlmAz39FiXWtO3eRY.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//21pDdAKAgfU2l0pgDmqEWpJAAHsTD3.jpg',
                'title' => 'Paket Data Indosat Murah',
                'highlight' => '',
                'terms' =>'<p>Paket Data Indosat Murah</p>',
                'activity' => 'telecom',
                'label' => '',
                'web' => '',
                'phone' => '',
                'email' => '',
                'time_start' => '2019-09-01 6:00:00',
                'time_end' => '2019-09-30 4:57:50',
                'group' => '',
                'params' => '{"id":"23","slug":"paket-data-1"}',
                'status' => '2',
            ],
            [
                'id' => '113',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//sa1R7Fws6Y1C9JJETgO1ZH4ymZf3NN.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//44sKm55xYgjegdP8a1MnWYuXPQiS2D.jpg',
                'title' => 'Paket Data Freedom Indosat',
                'highlight' => '',
                'terms' =>'<p>Paket Data Freedom Indosat </p>',
                'activity' => 'telecom',
                'label' => '',
                'web' => '',
                'phone' => '',
                'email' => '',
                'time_start' => '2019-08-01 9:23:51',
                'time_end' => '2019-08-31 16:59:00',
                'group' => '',
                'params' => '{"id":"23","slug":"paket-data-1"}',
                'status' => '2',
            ],
            [
                'id' => '114',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//xtLYJAiWPxIlQSFTncvIXXDsW02T1j.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//VtLMlRTBUprVLlF2ZyW1zUKXfHdkZ6.jpg',
                'title' => 'Pulsa Telkomsel',
                'highlight' => '',
                'terms' =>'<p>Pulsa Telkomsel</p>',
                'activity' => 'telecom',
                'label' => '',
                'web' => '',
                'phone' => '',
                'email' => '',
                'time_start' => '2019-08-01 9:23:51',
                'time_end' => '2019-08-31 4:57:50',
                'group' => '',
                'params' => '{"id":"19","slug":"pulsa-1"}',
                'status' => '2',
            ],
            [
                'id' => '115',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//tHe8Kxb5okCsMiDzzR8zsv5VOyXiPM.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//QM1F9nNoEn3xQXvn20AmMJC1223KBd.jpg',
                'title' => 'Promo Highground',
                'highlight' => 'Bertempat di daerah Pantai Indah Kapuk, lantai 1 jadi gaming roomnya, lantai 2 gaming room VIP, dan lantai 3 adalah hall untuk keperluan serbaguna, kayak turnamen, konser, bahkan nobar.',
                'terms' =>'"<ul>
                <li>Periode Promosi berlaku dari tanggal 10 Desember 2019 s/d 10 Maret 2020</li>
                <li>Maskimal cashback Rp. 50.000 dalam bentuk Ncash</li>
                <li>Maksimal cashback 50%/transaksi/akun</li>
                </ul>"',
                'activity' => 'info',
                'label' => '',
                'web' => '',
                'phone' => '021-27893342',
                'email' => 'info@nusapay.co.id',
                'time_start' => '2019-12-03 17:01:00',
                'time_end' => '2020-03-10 16:59:00',
                'group' => '',
                'params' => '[]',
                'status' => '2',
            ],
            [
                'id' => '117',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//7EiLFRTuB2bgtJPfBafsgb8hNiCOVX.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//o53ZHXsg0fHIC2q19horuTqFP5etp9.jpg',
                'title' => 'Promo Anak Garuda',
                'highlight' => '',
                'terms' =>'',
                'activity' => 'merchant_page',
                'label' => '',
                'web' => '',
                'phone' => '',
                'email' => '',
                'time_start' => '2019-09-05 7:06:34',
                'time_end' => '2019-12-31 16:59:59',
                'group' => '',
                'params' => '{"merchant_id":"59"}',
                'status' => '2',
            ],
            [
                'id' => '118',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//D2Y6RE4FkO77EQ7OpPlGtNBX3Tcacb.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//sI9cp4czJLzVH3YVXCLCT1Mfib94Z5.jpg',
                'title' => 'Pemberitahuan Pelanggan Indosat',
                'highlight' => '',
                'terms' =>'<p>Pemberitahuan Pelanggan Indosat</p>',
                'activity' => 'info',
                'label' => '',
                'web' => '',
                'phone' => '',
                'email' => '',
                'time_start' => '2019-10-03 7:38:03',
                'time_end' => '2019-10-10 7:38:07',
                'group' => '',
                'params' => '[]',
                'status' => '2',
            ],
            [
                'id' => '119',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//2p7N1fnecqiRaY9d5Aryi0ghhyjEja.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//dpQZmWVjuKFiHQtvhW4HWMDQ0q1VY8.jpg',
                'title' => 'Promo Mangan 20 oct - 20 nov 2019',
                'highlight' => '                ',
                'terms' =>'<p>- Hanya berlaku untuk makan ditempat<br />- Maksimal cashback Rp 300.000<br />- Maksimal cashback 2x transaksi/pengguna<br />- Promo hanya berlaku untuk ala carte &amp; non alcohol<br />- Promo tidak dapat digabung dengan promo lainnya</p>',
                'activity' => 'info',
                'label' => '',
                'web' => '',
                'phone' => '+622139503000',
                'email' => '',
                'time_start' => '2019-10-15 8:10:34',
                'time_end' => '2019-11-20 16:59:59',
                'group' => '',
                'params' => '[]',
                'status' => '2',
            ],
            [
                'id' => '120',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//IdL4pSCm9mMT5vNHP8e3R8B0k0XtZp.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//8hUILYJ02Kcn7lkZNkkSVGdK9Yf4gL.jpg',
                'title' => 'Promo Algusto 20 oct - 20 nov 2019',
                'highlight' => '',
                'terms' =>'<p>- Hanya berlaku untuk makan ditempat<br />- Maksimal cashback Rp 300.000<br />- Maksimal cashback 2x transaksi/pengguna<br />- Promo hanya berlaku untuk ala carte &amp; non alcohol<br />- Promo tidak dapat digabung dengan promo lainnya</p>',
                'activity' => 'info',
                'label' => '',
                'web' => '',
                'phone' => '(021) 39503000',
                'email' => '',
                'time_start' => '2019-10-15 8:20:44',
                'time_end' => '2019-11-20 16:59:59',
                'group' => '',
                'params' => '[]',
                'status' => '2',
            ],
            [
                'id' => '121',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//RuE3zfS8dPOpy7XrgpVirkL4eVSfF2.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//Lo6oWHbUXOUycR2BRVJCfs5M79iAs9.jpg',
                'title' => 'Promo Fufufu Bulan Desember 2019',
                'highlight' => 'We are a fast casual food shop, serving you ready-to-eat and ready-to-deliver home-cooked food. The name Fú Fū Fù comes from the character meaning of Fu. Left Fú means a husband, right Fù means a wife, and middle Fū is their precious little fortune.',
                'terms' =>'<p>- Periode Promosi 1-31 Desember 2019&nbsp;<br />- Cashback dalam bentuk saldo Ncash<br />- Tanpa minumum pembelian <br />- Promo cashback sebesar 30% <br />- Maksimal Cashback 20 rb/transaksi/akun/hari</p>',
                'activity' => 'info',
                'label' => '',
                'web' => 'https://fufufu.id/',
                'phone' => '811135855',
                'email' => '',
                'time_start' => '2019-10-30 17:00:01',
                'time_end' => '2019-11-30 16:59:59',
                'group' => '',
                'params' => '[]',
                'status' => '2',
            ],
            [
                'id' => '122',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//FgXfxf9etl4xPRzd9K1Z26f1JgmT4N.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//A7JMz3rgihQ1rKVzNbI9sA2SLLkaLb.jpg',
                'title' => 'Merchant Promo Bakso Jakarta',
                'highlight' => 'Bakso Jakarta di Mall WTC Matahari Serpong, berlokasi di Food Court Blok F-31 lantai Upper Ground. Buka setiap hari pukul 10.00 sampai dengan 22.00 WIB',
                'terms' =>'"<ul>
                <li>Maksimal cashback Rp. 5.000</li>
                <li>Promo cashback dalam bentuk saldo Ncash&nbsp;</li>
                <li>Promo berlaku 2x transaksi/hari/akun</li>
                </ul>"',
                'activity' => 'info',
                'label' => '',
                'web' => '',
                'phone' => '(021) 29422831',
                'email' => 'tokotanjungduren.grabfood@gmail.com',
                'time_start' => '2020-02-01 4:14:10',
                'time_end' => '2020-04-20 16:59:00',
                'group' => '',
                'params' => '[]',
                'status' => '2',
            ],
            [
                'id' => '123',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//TQ3mL17WBs3e27jSHDWan1sGMcoaBB.jpeg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//bJCwMHw9isKisjkQP3RF5bmMuM7jDx.jpeg',
                'title' => 'Fufufu Resto',
                'highlight' => 'Tempat makan super cozy dengan makanan non msg, bisa untuk gathering dan di lt 2 terdapat juga coffeshop',
                'terms' =>'<p>Cashback max 20.000/hari/pengguna</p>',
                'activity' => 'info',
                'label' => '',
                'web' => '',
                'phone' => '811135855',
                'email' => '',
                'time_start' => '2019-12-01 7:33:19',
                'time_end' => '2019-12-31 7:33:10',
                'group' => 'wallet',
                'params' => '[]',
                'status' => '2',
            ],
            [
                'id' => '124',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//z7VDKOuvYa73Njvn8L9ysc8SXzGihR.jpg',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//1Z377jF0nuLaXa4QsHhMxRZcDTDpxc.jpg',
                'title' => 'Tiket Premier Anak Garuda HDI',
                'highlight' => 'Promo pembelian tiket nonton film bisokop Anak Garuda di HDI Kelapa Gading dengan menggunakan aplikasi Nusapay',
                'terms' =>'"<ul>
                <li>Periode promosi : 17 Desember 2019 - 31 Januari 2020</li>
                <li>Promo cashback 50% pembayaran menggunakan aplikasi Nusapay&nbsp;</li>
                <li>Maximal cashback 20 rb/transaksi/akun/hari</li>
                </ul>"',
                'activity' => 'merchant_page',
                'label' => '',
                'web' => '',
                'phone' => '89663157787',
                'email' => '',
                'time_start' => '2019-12-17 2:48:34',
                'time_end' => '2020-01-31 2:48:39',
                'group' => '',
                'params' => '{"merchant_id":"61"}',
                'status' => '2',
            ],
            [
                'id' => '125',
                'image' => 'https://media.um0phbmlhwn0qyay58pf.click/image//o0NuFY0IjCrlt6SZo52OyeCy0ZfVM0.png',
                'cover' => 'https://media.um0phbmlhwn0qyay58pf.click/image//o0NuFY0IjCrlt6SZo52OyeCy0ZfVM0.png',
                'title' => 'Carstensz Promotion banner',
                'highlight' => 'Carstensz Apartement & Mall located in the heart of Gading Serpong, aims to be the epicenter of everything with various kind of facilities than can be reached in less than 15 minutes',
                'terms' =>'"<p>Get it fast, limited unit, Terms &amp; Conditions&nbsp; Applied</p><p>
                </p><p>Check out more information&nbsp; at&nbsp;<a href=""http://carstenszresidence.com"" target=""_blank"">http://carstenszresidence.com</a></p><p>or call&nbsp;</p><p>021-2222-7999</p>"',
                'activity' => 'info',
                'label' => '',
                'web' => 'https://carstenszresidence.com',
                'phone' => '021-2222-7999',
                'email' => 'Info@carstenszresidence.com',
                'time_start' => '2021-03-02 15:00:40',
                'time_end' => '2021-04-30 23:00:46',
                'group' => 'nusapay',
                'params' => '[]',
                'status' => '2',
            ]

        ]);
    }
}
