<?php

namespace Database\Seeders\Docs;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HelpSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $company = config('company.info');
        $pt = $company['name'];
        $brand = $company['brand'];
        DB::table('docs.help')->insert([
            [
                'id' => '1',
                'user' => '5',
                'category' => '1',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Mengenal Cashtag',
                'content' => '<h3>Cashtag</h3>rn<p>Cashtag adalah fitur yang memungkinkan nama nasabah sebagai nomor rekening, sehinga Anda tidak perlu lagi repot menghafal nomer rekening yang panjang.</p>rn<p>Nama @Cashtag ini unik dan tidak akan sama dengan nasabah yang lainnya. Selain itu @Cashtag juga bisa mendukung bisnis online, misalnya membuat nama @Cashtag sesuai dengan nama toko atau produk yang dijual. Karena nama @Cashtag bisa dipilih sesuai dengan keinginan pengguna dan lebih personal, tidak harus menggunakan nama pemilik.</p>rn<p>Gunakan @Cashtag untuk mentransfer dana ke sesama pengguna '.$brand.' dan dapatkan Poin dengan mereferensikan @Cashtag Anda ke teman-teman untuk menggunakan '.$brand.'.</p>rn<p>&nbsp;</p>',
                'keywords' => '["cashtag"]',
            ],
            [
                'id' => '2',
                'user' => '5',
                'category' => '1',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Tutup Akun '.$brand.'',
                'content' => '<h3>Tutup Akun</h3>rn<p>Tutup akun adalah permanen dan tidak dapat dipulihkan kembali. Setelah akun Anda sukses di tutup &amp; di hapus, Anda tidak akan dapat login/masuk dan melihat riwayat akun Anda lagi.</p>rn<p>Anda dapat mengikuti langkah berikut untuk tutup akun '.$brand.' :</p>rn<ol>rn<li>Pilih menu Akun</li>rn<li>Pilih Keamanan &amp; Perlindungan&nbsp;</li>rn<li>Pilih Tutup Akun</li>rn<li>Pilih "Hapus &amp; Tutup Akun"</li>rn<li>Isi beberapa pertanyaan</li>rn<li>Klik "Saya menyetujui dan Telah Membaca Persyaratan Berlaku"</li>rn<li>Masukan kode OTP sebagai konfirmasi penutupan akun</li>rn</ol>rn<p>Saldo tersisa pada akun yang telah tertutup akan hangus dan Akun anda tidak dapat diakses kembali.</p>',
                'keywords' => '["tutup","tutup akun","akun"]',
            ],
            [
                'id' => '3',
                'user' => '5',
                'category' => '1',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Verifikasi Akun '.$brand.'',
                'content' => '<h3>Verifikasi Akun</h3>rn<p>Untuk mengantisipasi resiko kejahatan pencucian uang (<em>money laundering</em>) dan penipuan pada pelaksanaan transaksi di '.$brand.' maka sesuai dengan <strong>Peraturan Bank Indonesia (PBI)</strong> <strong>nomor</strong> <strong>20/6/PBI/2018</strong> tentang uang elektronik. Beserta peraturan peraturan lainnya yang terkait, maka '.$brand.' membutuhkan setiap pengguna yang ingin menaikkan batas limit saldo dari&nbsp;&nbsp;<strong>IDR 2.000.000</strong> ( Dua Juta Rupiah ) menjadi <strong>IDR 10.000.000</strong> ( Sepuluh Juta Rupiah ) bagi pengguna yang telah melakukan verifikasi akun</p>rn<h3>Tata Cara Verfikasi Akun</h3>rn<p>Tata cara melakukan verifikasi di '.$brand.' adalah sebagai berikut :</p>rn<ol>rn<li>Melengkapi data pada aplikasi '.$brand.'</li>rn<li>Memilih Kewarga Negaraan</li>rn<li>Foto Identitas Berlaku (KTP / Paspor)</li>rn<li>Foto diri dengan Identitas Berlaku (KTP / Paspor)</li>rn<li>Mengisi Nama Gadis Ibu Kandung</li>rn<li>Mengisi Tipe Pekerjaan</li>rn</ol>rn<p>Setelah berhasil melakukan <em>submit&nbsp;</em>maka Tim '.$brand.' akan melakukan pengecekan apakah semua data yang Anda telah masukan benar, jika semua data telah benar maka akun Anda akan segera terverifikasi.</p>rn<p>Lama proses untuk verifikasi Akun adalah <br />1 x 24 Jam kerja jika proses verfikasi Anda lebih lama dari waktu tersebut mohon hubungi Tim '.$brand.' di :</p>rn<p>Whatsapp&nbsp;<strong>089 7889 7889</strong>&nbsp;| Telegram&nbsp;<strong>089 7889 7889</strong>&nbsp;| Facebook&nbsp;<strong>'.$brand.'id</strong>&nbsp;| Twitter <strong>@'.$brand.'id</strong> | Email&nbsp;<strong>info@'.$brand.'.co.id</strong></p>',
                'keywords' => '["verifikasi akun","kyc"]',
            ],
            [
                'id' => '4',
                'user' => '5',
                'category' => '1',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Kelola akun di Perangkat Berbeda',
                'content' => '<h3>Kelola Akun</h3>rn<p>Aplikasi '.$brand.' dapat digunakan dibeberapa perangkat berbeda secara bersamaan. Namun kami tidak mengabaikan faktor keamanan Anda, perangkat yang masuk akan tercatat pada halaman Manajemen Perangkat untuk menambahkan perangkat lain caranya adalah sebagai berikut :</p>rn<ol>rn<li>Masuk pada halaman Manajemen Perangkat</li>rn<li>Pilih Tombol Tambah Perangkat</li>rn<li>Masukan Kode OTP pada perangkat Lainnya</li>rn</ol>rn<p><em>&nbsp;</em>dan Akun utama akan mendapatkan Pemberitahuan berupa <em>Apps Notifikasi</em> dan <em>Email Notifikasi.</em></p>rn<h3>Sesi Aktif</h3>rn<p>Anda dapat melihat setiap perangkat yang mengakses akun Anda melalui :&nbsp;</p>rn<ol>rn<li>Pilih halaman Manajemen Perangkat</li>rn<li>Klik Sesi Aktif</li>rn<li>Pilih Akhiri Sesi lainnya untuk mengeluarkan akun pada perangkat lainnya terkecuali Perangkat Utama</li>rn</ol>rn<p>Jika Anda merasa ada perangkat yang tidak Anda kenali maka anda dapat melakukan pengakhiran sesi pada sesi yang dipilih atau mengakhiri semua sesi lainnya untuk mengeluarkan akun pada perangkat lainnya terkecuali Perangkat Utama.</p>rn<p>&nbsp;</p>',
                'keywords' => '["multi login","login","akun"]',
            ],
            [
                'id' => '5',
                'user' => '5',
                'category' => '2',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Apa Itu Nusaku',
                'content' => '<h3>Nusaku</h3>rn<p>Nusaku merupakan dompet elektronik milik setiap pengguna '.$brand.', berfungsi untuk menampung saldo dan melakukan pencatatan transaksi digital pada aplikasi '.$brand.'.</p>rn<h3>Saldo</h3>rn<p>Saldo '.$brand.' adalah dana yang Anda simpan di akun '.$brand.', dengan saldo '.$brand.', Anda dapat melakukan pembelian dan pembayaran setiap produk yang tersedia pada layanan '.$brand.'. Saldo '.$brand.' menggunakan mata uang Rupiah dan dapat diisi (Top Up) melalalui transfer bank atau <em>Virtual Account</em>.</p>',
                'keywords' => '',
            ],
            [
                'id' => '6',
                'user' => '5',
                'category' => '2',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Berapa Batas Limit Saldo '.$brand.'',
                'content' => '<h3>Limit Saldo</h3>rn<p>Berdasarkan Peraturan Bank Indonesia <strong>Nomor 20/6/PBI/2018</strong> tentang Uang Elektronik. Pengguna uang elektornik dapat memiliki dana sebesar <strong>IDR 2.000.000</strong> (dua juta rupiah) dan dapat di tingkatkan menjadi <strong>IDR 10.000.000</strong> (sepuluh juta rupiah) dengan melakukan verifikasi akun. Dengan batas nilai transaksi 1 (satu) bulan yang dihitung dengan Transfer Masuk (Incoming Transfer) sebesar <strong>IDR 20.000.000</strong>&nbsp;(dua puluh juta rupiah).</p>',
                'keywords' => '',
            ],
            [
                'id' => '7',
                'user' => '5',
                'category' => '2',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Riwayat Transaksi Saldo '.$brand.'',
                'content' => '<h3>Riwayat Transaksi</h3>rn<p>Untuk dapat melihat riwayat transaksi dari penggunaan Saldo, silahkan ikuti langkah berikut ini :</p>rn<ol>rn<li>Pilih Akun Saya ( My Account )</li>rn<li>Pilh Dompet Saya ( My Wallet )</li>rn<li>Pilih Riwayat ( History )</li>rn</ol>rn<p>Anda dapat melakukan penyaringan dan juga menandai setiap Transaksi dengan beragam pilihan Label untuk mempermudah Anda dalam membaca riwayat Transaksi.</p>',
                'keywords' => '',
            ],
            [
                'id' => '8',
                'user' => '5',
                'category' => '2',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Saldo Berkurang Transaksi Masih Dalam Proses',
                'content' => '<h3>Saldo Sedang di proses</h3>rn<p>Jika status transaksi menunjukkan &ldquo;Sedang di proses&rdquo;, artinya transaksi Anda sedang diproses. Saldo akan dipotong terlebih dahulu karena transaksi Anda sudah diterima untuk diproses oleh sistem '.$brand.'. Namun jika ada kegagalan saat diproses oleh sistem dan saldo Anda tidak / belum dikembalikan, sebaiknya Anda melakukan konfirmasi kepada Layanan Pengguna kami.</p>rn<p>Whatsapp&nbsp;<strong>089 7889 7889</strong>&nbsp;| Telegram&nbsp;<strong>089 7889 7889</strong>&nbsp;| Facebook&nbsp;<strong>'.$brand.'id</strong>&nbsp;| Twitter <strong>@'.$brand.'id</strong> | Email&nbsp;<strong>info@'.$brand.'.co.id</strong></p>',
                'keywords' => '',
            ],
            [
                'id' => '9',
                'user' => '5',
                'category' => '2',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Saldo Tidak Bertambah Setelah Pengisian',
                'content' => '<div class="page" title="Page 16">rn<div class="section">rn<div class="layoutArea">rn<div class="column">rn<h3>Saldo tidak bertambah</h3>rn<p>Setelah Anda berhasil melakukan transaksi pada Bank Anda, segera lakukan konfrmasi pada aplikasi '.$brand.' dengan klik tombol &ldquo;Saya Telah <em>Top Up</em>&rdquo;, saldo Anda akan bertambah dalam beberapa menit. Namun, jika Saldo '.$brand.' Anda tidak bertambah, ikuti langkah berikut ini :</p>rn<ul>rn<li><strong>Virtual Account :&nbsp;<br /></strong>Sebelum konfirmasi pembayaran, pastikan nama akun tujuan yang akan diisi sudah benar. Apabila terjadi kesalahan pada nomor akun yang berakibat pada kesalahan tujuan transfer, maka hal tersebut bukan merupakan tanggung jawab '.$brand.'</li>rn<li><strong> Bank Transfer :&nbsp;<br /></strong>1. Cek bukti transfer Anda, pastikan transaksi sudah berhasil<br />2. Pastikan Anda memasukkan nomor rekning '.$brand.' terdaftar di aplikasi '.$brand.'<br />3. Pastikan Anda memasukkan nominal yang ditagihkan sesuai pada Detail Top Up<br />4. Pastikan waktu pembayaran Anda tidak melebihi tenggang waktu yang diberikan (Order ID akan kadaluarsa dalam waktu 2 jam)<br />5. Tunggu hingga maksimal 1 jam</li>rn</ul>rn<div class="page" title="Page 17">rn<div class="layoutArea">rn<div class="column">rn<p>Jika saldo '.$brand.' Anda belum diterima dalam waktu maksimal (&lt;= 1 jam) pada jam operasional yaitu <strong>WIB&nbsp;07:00-22:00</strong>, silahkan menghubungi pelayanan pelanggan (Customer Service) '.$brand.' melalui emali dengan menyebutkan order ID dan Bukti Transfer ke <strong>info@'.$brand.'.co.id</strong> untuk pengecekan ulang transaksi oleh tim kami atau telpon ke <strong>+62 89 7889 7889</strong></p>rn</div>rn</div>rn</div>rn</div>rn</div>rn</div>rn</div>',
                'keywords' => '',
            ],
            [
                'id' => '10',
                'user' => '5',
                'category' => '2',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Transfer ke Pengguna '.$brand.' Lain',
                'content' => '<h3>Transfer</h3>rn<p>Anda dapat melakukan Transfer Saldo ke sesama pengguna aplikasi '.$brand.', dengan ketentuan Penerima telah di <strong>"Verfikasi"</strong> statusnya oleh '.$brand.'.&nbsp;</p>rn<p>Untuk melakukan Transfer Saldo ke Pengguna lain caranya adalah sebagai berikut :</p>rn<ol>rn<li>Pilih Transfer pada Halaman Beranda / Dompet Saya</li>rn<li>Pilih Nusaku ( Dompet Elektronik '.$brand.')</li>rn<li>Isi Tujuan, berupa nomer Telepon atau @Cashtag</li>rn<li>Konfirmasi Tujuan</li>rn<li>Isi Jumlah Nominal</li>rn<li>Isi Catatan Transfer</li>rn<li>Pilih Post Card dan Konfrimasi&nbsp;</li>rn<li>Pilih Transfer Sekarang</li>rn<li>&nbsp;Isi PIN Transaksi</li>rn</ol>rn<p>Pengirim akan mendapatkan Laporan Transaksi "<strong>Berhasil</strong>" sebagai bukti telah terkirimnya Saldo ke Pengguna lain.</p>rn<h3>Ketentuan</h3>rn<ul>rn<li>Batas minimum saldo transaksi pengiriman adalah<strong> IDR. 10.000 </strong>( Sepuluh Ribu Rupiah )&nbsp;</li>rn<li>Batas maksimum saldo pengiriman Sejumlah limit Bulanan pada Dompet Elektronik '.$brand.' yaitu<strong> IDR.10.000.000&nbsp;</strong>(Sepuluh<br />Juta Rupiah )</li>rn</ul>rn<p>&nbsp;</p>',
                'keywords' => '',
            ],
            [
                'id' => '13',
                'user' => '5',
                'category' => '2',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Isi Saldo '.$brand.'',
                'content' => '<h3>Isi Saldo '.$brand.'</h3>rn<p>Untuk melakukan pengisian saldo '.$brand.' ada beberapa cara yang dapat Anda ikutin, caranya sebagai berikut :</p>rn<ul>rn<li>Pilih Isi Saldo pada halaman beranda / dompet saya</li>rn<li>Terdapat pilihan Bank Transfer / Virtual Account / Isi dengan Agen</li>rn</ul>rn<h3>Bank Transfer</h3>rn<p>Untuk melakukan Isi saldo melalui Bank Transfer Anda dapat melakukannya sebagai berikut :</p>rn<ul>rn<li>Pilih Bank Transfer pada halaman Isi Saldo</li>rn<li>Pilih Bank Tujuan</li>rn<li>Masukan nominal&nbsp;</li>rn<li>Cek Rekening Tujuan</li>rn<li>Transfer dengan Kode Unik yang disediakan</li>rn<li>Pilih Saya telah Transfer untuk memproses</li>rn</ul>rn<p>Kode Unik dibutuhkan untuk&nbsp;mempermudah dan mempercepat proses verifikasi pembayaran Anda.</p>rn<h3>Virtual Account</h3>rn<p>Untuk melakukan Isi saldo melalui Virtual Account Anda dapat melakukannya sebagai berikut :</p>rn<ul>rn<li>Lakukan pada Aplikasi / Mesin Bank Tujuan</li>rn<li>Pilih Virtual Account</li>rn<li>Masukan Nominal yang di inginkan</li>rn<li>Submit / Proses</li>rn</ul>rn<p>Mungkin terdapat biaya pada&nbsp;transaksi menggunakan virtual account.</p>rn<h3>Isi dengan Agen</h3>rn<p>Untuk melakukan Isi saldo melalui Agen '.$brand.' Anda dapat melakukannya sebagai berikut :</p>rn<ul>rn<li>Pilih Isi dengan Agen pada halaman Isi Saldo</li>rn<li>Masukan kode agen "@Cashtag"</li>rn<li>Isi nominal yang di inginkan</li>rn<li>Konfirmasi dan berikan Nominal yang disetujui pada Agen</li>rn</ul>rn<p>Mungkin terdapat biaya pada transaksi menggunakan Agen.</p>',
                'keywords' => '',
            ],
            [
                'id' => '14',
                'user' => '5',
                'category' => '2',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Apa itu NCash / Cashback',
                'content' => '<h3>NCash</h3>rn<p>NCash merupakan tempat penampungan saldo promosi cashback yang dilakukan oleh pihak '.$brand.'. Saldo NCash dapat dilakukan untuk pembelianjaan produk-produk digital yang berada pada Aplikasi '.$brand.'. Saldo NCash tidak dapat di transfer atau di rubah kepemilikannya.</p>rn<h3>Cashback</h3>rn<p>Cash Back secara umum adalah bentuk potongan harga jual untuk konsumen / pelanggan dan pemberlakuannya di belakang atau setelah transaksi. Pemberlakuan potongan di belakang maksudnya setelah pembeli melakukan pembayaran tunai ataupun down payment (untuk pembelian kredit) dan kadang disertai syarat tertentu. Misal Mobil seharga Rp 200.000.000,- dengan down payment Rp 35.000.000,- cash back Rp 7.000.000,- .</p>rn<p>Artinya setelah pembeli membayar uang muka dan mobil diterima, baru pembeli akan memeroleh pengembalian uang Rp 7.000.000,-. Atau mungkin saja pengembalian uang tadi dilakukan saat pembayaran angsuran pertama dan lain sebagainya.</p>',
                'keywords' => '',
            ],
            [
                'id' => '15',
                'user' => '5',
                'category' => '2',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Tarik Saldo '.$brand.'',
                'content' => '<h3>Tarik Saldo '.$brand.'</h3>rn<p>Untuk melakukan penarikan saldo '.$brand.' ada beberapa cara yang dapat Anda ikutin, caranya sebagai berikut :</p>rn<ul>rn<li>Pilih Transfer pada halaman beranda / dompet saya</li>rn<li>Terdapat pilihan Bank Transfer / Tarik dengan Agen</li>rn</ul>rn<p>Untuk menarik saldo '.$brand.' Pengguna harus sudah terverifikasi.</p>rn<h3>Bank Transfer</h3>rn<p>Untuk melakukan Isi saldo melalui Bank Transfer Anda dapat melakukannya sebagai berikut :</p>rn<ul>rn<li>Pilih Bank Transfer Bank Lokal pada halaman Transfer&nbsp;</li>rn<li>Masukan detail rekening Bank Tujuan</li>rn<li>Masukan nominal</li>rn<li>Konfirmasi</li>rn<li>Pilih Transfer Sekarang</li>rn</ul>rn<p>Mungkin terdapat biaya pada&nbsp;transaksi penarikan saldo. Proses Tarik saldo dilakukan dalam kurun waktu 1-2 Hari kerja.</p>rn<p>&nbsp;</p>rn<h3>Tarik dengan Agen</h3>rn<p>Untuk melakukan Tarik saldo melalui Agen '.$brand.' Anda dapat melakukannya sebagai berikut :</p>rn<ul>rn<li>Pilih Tarik dengan Agen pada halaman Transfer</li>rn<li>Masukan kode agen "@Cashtag"</li>rn<li>Isi nominal yang di inginkan</li>rn<li>Konfirmasi Saldo dan Terima Dana yang diberikan Agen</li>rn</ul>rn<p>Tidak semua agen dapat memproses penarikan saldo '.$brand.', mungkin terdapat biaya pada penarikan saldo menggunakan Agen.</p>',
                'keywords' => '',
            ],
            [
                'id' => '20',
                'user' => '5',
                'category' => '4',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Pulsa & Paket Data',
                'content' => '<h3>Pulsa</h3>rn<p>Untuk melakukan pembelian pulsa, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman Pulsa &amp; Paket Data</li>rn<li>Isi nomer selular pra bayar</li>rn<li>Pilih nominal Pulsa</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<h3>Paket Data</h3>rn<p>Untuk melakukan pembelian paket data, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman Pulsa &amp; Paket Data</li>rn<li>Isi nomer selular pra bayar</li>rn<li>Pilih Paket Data</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>',
                'keywords' => '',
            ],
            [
                'id' => '21',
                'user' => '5',
                'category' => '4',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'PLN',
                'content' => '<h3>Token PLN</h3>rn<p>Untuk melakukan pembelian token pln, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman PLN</li>rn<li>Isi nomer meter / nomer pelanggan</li>rn<li>Pilih nominal Token Listrik</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<h3>Tagihan PLN&nbsp;</h3>rn<p>Untuk melakukan pembayaran Tagihan PLN, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman PLN</li>rn<li>Pilih Tagihan PLN</li>rn<li>Isi nomer Pelanggan</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<h3>Non Tagihan Listrik</h3>rn<p>Untuk melakukan pembayaran Non Tagihan Listrik PLN, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman PLN</li>rn<li>Pilih Non Tagihan Listrik</li>rn<li>Isi nomer Pelanggan</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>',
                'keywords' => '',
            ],
            [
                'id' => '22',
                'user' => '5',
                'category' => '4',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Mutifinance',
                'content' => '<h3>Multifinance</h3>rn<p>Untuk melakukan pembayaran multifinance, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman Multifinance</li>rn<li>Pilih Provider Multifinance</li>rn<li>Isi nomer Kontrak</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<p>&nbsp;</p>',
                'keywords' => '',
            ],
            [
                'id' => '23',
                'user' => '5',
                'category' => '4',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'PDAM',
                'content' => '<h3>PDAM</h3>rn<p>Untuk melakukan pembayaran pdam, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman PDAM</li>rn<li>Pilih Daerah</li>rn<li>Isi nomer pelanggan</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<p>&nbsp;</p>',
                'keywords' => '',
            ],
            [
                'id' => '24',
                'user' => '5',
                'category' => '4',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Telkom',
                'content' => '<h3>Telkom Telepon</h3>rn<p>Untuk melakukan pembayaran tagihan telepon telkom, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman Telkom</li>rn<li>Pilih Telepon</li>rn<li>Isi nomer Pelanggan</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<h3>Telkom Internet&nbsp;</h3>rn<p>Untuk melakukan pembayaran Tagihan Speedy / Indihome, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman Telkom</li>rn<li>Pilih Internet</li>rn<li>Isi nomer Pelanggan</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<h3>Wifi.Id</h3>rn<p>Untuk melakukan pembelian Telkom Wifi.Id, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman Telkom</li>rn<li>Pilih Wifi.Id</li>rn<li>Pilih nominal / paket</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>',
                'keywords' => '',
            ],
            [
                'id' => '25',
                'user' => '5',
                'category' => '4',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Telepon Selular Pasca Bayar',
                'content' => '<h3>Selular Pasca Bayar</h3>rn<p>Untuk melakukan pembayaran selular pasca bayar, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman Selular Pasca Bayar</li>rn<li>Pilih Provider</li>rn<li>Isi nomer pelanggan</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<p>&nbsp;</p>',
                'keywords' => '',
            ],
            [
                'id' => '26',
                'user' => '5',
                'category' => '4',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Game Voucher',
                'content' => '<h3>Game Voucher</h3>rn<p>Untuk melakukan pembelian game voucher, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman Game Voucher</li>rn<li>Pilih Provider Game Voucher</li>rn<li>Pilih nominal / point / voucher</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran. Beberapa Provider meminta Game ID Pelanggan.</p>',
                'keywords' => '',
            ],
            [
                'id' => '27',
                'user' => '5',
                'category' => '4',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'BPJS',
                'content' => '<h3>BPJS Kesehatan</h3>rn<p>Untuk melakukan pembayaran BPJS, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman BPJS</li>rn<li>Isi nomer Kepersertaan BPJS</li>rn<li>Pilih Bulan yang di bayarkan</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<h3>BPJS Ketenagakerjaan</h3>rn<p>Layanan BPJS Ketenagakerjaan Segera Hadir.</p>',
                'keywords' => '',
            ],
            [
                'id' => '28',
                'user' => '5',
                'category' => '4',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Asuransi',
                'content' => '<h3>Asuransi</h3>rn<p>Untuk melakukan pembayaran asuransi, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman Asuransi</li>rn<li>Pilih Provider Asuransi</li>rn<li>Isi nomer Polis</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<p>&nbsp;</p>',
                'keywords' => '',
            ],
            [
                'id' => '29',
                'user' => '5',
                'category' => '4',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'TV Kabel & TV Berlangganan',
                'content' => '<h3>TV Kabel</h3>rn<p>Untuk melakukan pembelian TV Kabel, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman TV Berbayar</li>rn<li>Pilih Provider</li>rn<li>Pilih paket</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<h3>TV Berlangganan&nbsp;</h3>rn<p>Untuk melakukan pembayaran TV Berlangganan, anda dapat mengikuti cara berikut ini :</p>rn<ul>rn<li>Pilih Halaman TV Berbayar</li>rn<li>Pilih Provider</li>rn<li>Isi nomer Pelanggan</li>rn<li>Pilih Bayar</li>rn</ul>rn<p>Pastikan Anda melakukan konfirmasi sebelum melakukan pembayaran.</p>rn<p>&nbsp;</p>',
                'keywords' => '',
            ],
            [
                'id' => '31',
                'user' => '5',
                'category' => '6',
                'locale' => 'en-US',
                'group' => 'user',
                'title' => 'What is Cashtag ',
                'content' => '<h3>Cashtag</h3>rn<p>Cashtag is a feature that allows the customer\'s name as an account number, so you no longer have to bother memorizing long account numbers.</p>rn<p>This @Cashtag name is unique and will not be the same as other customers. In addition @Cashtag can also support online businesses, for example, making the name @Cashtag according to the name of the store or product sold. Because the name @Cashtag can be chosen according to the user\'s wishes and is more personal, it doesn\'t have to use the owner\'s name.</p>rn<p>Use @Cashtag to transfer funds to fellow '.$brand.' users and get NCash Balance or Points by referring your @Cashtag to friends to use '.$brand.'.</p>',
                'keywords' => '["cashtag"]',
            ],
            [
                'id' => '32',
                'user' => '5',
                'category' => '10',
                'locale' => 'id-ID',
                'group' => 'user',
                'title' => 'Hubungi Kami',
                'content' => '<p>Jika anda memiliki masalah terhadap pelayanan kami. Anda dapat menghubungi kami di :</p>rn<p>WA 089-7889-7889 | Telegram WA 089-7889-7889 | Facebook fb.me/'.$brand.'id | Twitter @'.$brand.'id | Email info@'.$brand.'.co.id</p>',
                'keywords' => '',
            ]
        ]);
    }
}
